# IRCd Parameters
nick: paprika1234
# make sure to add the port at the end with a colon
host: irc.rizon.net:6667
# use the word true or false for this field
tls: false

# Sever password, sent as ("PASS :%s", pass)
#pass: yourpass

# SASL password (cert support tbd) for nickserv identification
#sasl: mynickserv-pass

# database, and other state, directory
# defaults to XDG_DATA_HOME or
# STATE_DIRECTORY if using StateDirectory= in a systemd service unit file
#db-path: /var/lib/mybot/state

# a newline delimited list of channels
channels:
  - '#taigobot-test'

# : by itself terminates a list
# API Keys are stored in a map by IDENT: value
#api-keys:
#  - somesite: somekey
